server:
  port: 19872
spring:
  application:
    name: ms-product
  session:
    jdbc:
      initialize-schema: always
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
      show_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/product_db?currentSchema=product_sh
    username: postgres
    password:  1qaz@WSX
  flyway:
    enabled: true
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true